### ISSUE TITLE
Auto-generate configs

### ISSUE THREAD

**Issue by tomyumm-ge** [nxshock/gron#1]
> Usage
> Create gron.d directory

make this dir

> Create job config in gron.d/job1.conf ([TOML](https://en.wikipedia.org/wiki/TOML) format):

write some samples into gron.d directory

Thank you
from archlinuxoid

**Comment by nxshock** [comment]
Resolved in efa20ae0f0321ca36349041c6fe79116b201df14 and b118d185162d51b32d6cf4d8f72eb04a1d2a77f4.
